finish toggle
devtanole/m2-1224-code-solutions pull request #10
Opened 2024-12-14 09:14 UTC by devtanole

<img width="1792" alt="Screenshot 2024-12-14 at 1 05 23 AM" src="https://github.com/user-attachments/assets/78e7f509-cb44-4dde-b5ee-d4787e44aeaa" />

2024-12-17 01:34 UTC, gerardoh13 commented on react-toggle-switch/my-react-app/src/ToggleSwitch.tsx
Your ToggleSwitch should be in here.

2024-12-17 01:36 UTC, gerardoh13 commented on react-toggle-switch/my-react-app/src/App.tsx
> +      <button
Looks good! just move this to the ToggleSwitch.tsx file and add a "ON" "OFF" label.

2024-12-17 01:37 UTC, gerardoh13 requested changes
I like your approach. 
Let's just make sure we don't have empty files.

2024-12-17 09:36 UTC, devtanole commented
<img width="1792" alt="Screenshot 2024-12-17 at 1 34 45 AM" src="https://github.com/user-attachments/assets/4997c65c-bfd3-49ba-983e-b06591979642" />

2024-12-18 01:02 UTC, gerardoh13 approved these changes
Looks good!

2025-01-09 17:19 UTC, merged